name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:

  # Normalize composer.json
  composer-normalize:
    name: Normalize composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Normalize composer.json
        uses: docker://ergebnis/composer-normalize-action:latest
      - name: Commit normalized composer.json
        uses: EndBug/add-and-commit@v8
        with:
          message: Normalize composer.json

  # Unit tests
  test:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ 8.1 ]
        stability: [ lowest, stable ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Install dependencies
        run: composer update --prefer-${{ matrix.stability }} --prefer-dist --no-interaction
      - name: Run tests
        run: composer ci:test

  # Static Analysis
  analyse:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction
      - name: Run static analysis
        run: composer analyse
